### ISSUE TITLE
Preferences window duplicate fields bug

### ISSUE THREAD

**Issue by michaeldong** [airbnb/Lona#131]
![image](https://user-images.githubusercontent.com/1925773/37823392-5068b12c-2ec4-11e8-88f9-ca99c9849dbb.png)

When I tap some or none , It becomes this.  "the master" branch.

**Comment by dabbott** [comment]
Yeah -- this preferences screen is absolutely terrible, but there shouldn't be any reason to use it anymore... so I'm gonna leave it. I'll redo it whenever I need people to use preferences again

**Comment by michaeldong** [comment]
Thanks.

**Comment by dabbott** [comment]
Fixed
