### ISSUE TITLE
Lona should be able to edit colors and typography files

### ISSUE THREAD

**Issue by haswalt** [airbnb/Lona#14]
I'd like to see Lona be able to edit the workspace configuration so that it doesn't need to be created before using the workspace.

Happy to take up some of these issues.

**Comment by dabbott** [comment]
Yes, absolutely!

As a first step, I think we could try to make workspace colors editable from within the color picker. Currently we have:

![screen shot 2017-11-25 at 9 32 32 am](https://user-images.githubusercontent.com/1198882/33232966-286e6e44-d1c4-11e7-8046-9e454ba7b1e8.png)

I think it'd make sense to be able to at least add a color, and possibly edit colors from here. Eventually I want there to be an all-in-one place to edit the workspace configuration, without first having to open a component file. But I think that can come later (depends on https://github.com/airbnb/Lona/issues/11), and when it does, it'll re-use the same stuff we build for editing workspace colors directly from the picker.

@haswalt If you're interested, do you want to try to do this? We'd first want to figure out exactly what the UI looks like, but I think overall it wouldn't be _too_ much work (although definitely not trivial either).

**Comment by haswalt** [comment]
@dabbott Sure i'll have a go.

**Comment by dabbott** [comment]
@haswalt do you want to figure out the design also? Or should I make a wireframe or what this'd look like?

**Comment by haswalt** [comment]
I'm happy to have a look at the design. I'll throw up some wireframes when I get some time soon

**Comment by dabbott** [comment]
This is mostly possible now.
