### ISSUE TITLE
Building in Xcode 9.2

### ISSUE THREAD

**Issue by sogen** [airbnb/Lona#142]
## Submitting a Bug Report

Trying to build Lona in Xcode 9.2, OSX Sierra

## Expected Behavior

Build is successfull

## Current Behavior

Build fails,
getting errors about `compactMap`

the issue so far seems to be that Xcode 9.2 is the last supported version on OS X Sierra, and this Xcode runs Swift 4.0.
I'd need to install High Sierra, to install Xcode 9.3, to support Swift 4.1, to build Lona?

**Comment by andex** [comment]
@sogen Hi, I have same problem, how you resolved it?

**Comment by sogen** [comment]
Hi, used High Sierra
