### ISSUE TITLE
README.md link to broken

### ISSUE THREAD

**Issue by jonfelske** [airbnb/Lona#157]
## Submitting a Bug Report

Broken link in studio/README.md to file format docs.  Found them one folder up:

404 link ->https://github.com/airbnb/Lona/blob/master/studio/docs/file-formats/README.md
working link ->https://github.com/airbnb/Lona/blob/master/docs/file-formats/README.md

Fix on line 34: "../docs/file-formats/README.md "

FYI this is an awesome project.  Would love to help contribute.

**Comment by ryngonzalez** [comment]
Fixed with #161
