### ISSUE TITLE
Error while trying to generate Swift code from Lona/examples/test

### ISSUE THREAD

**Issue by ondermerol** [airbnb/Lona#169]
I get this error while trying to generate Swift code with this command "./node_modules/.bin/lonac workspace swift ../../examples/test/ ../../examples/output/" in compiler/core/
I am not sure if I make something wrong or not.

<img width="811" alt="screen shot 2018-07-17 at 23 24 45" src="https://user-images.githubusercontent.com/7923958/42843392-a264c286-8a18-11e8-869b-77493cb1afd9.png">

**Comment by dabbott** [comment]
Ah, I think the version I published on npm is fairly out of date since I haven't been using it lately. I would try building the compiler in `compiler/core` and running `yarn snapshot` to verify it's working correctly

**Comment by dabbott** [comment]
Updated readme to clarify
