### ISSUE TITLE
Future of the Lona

### ISSUE THREAD

**Issue by sercand** [airbnb/Lona#170]
What is the future of the Lona studio after @dabbott left the company?

**Comment by ljharb** [comment]
Unchanged, as far as i know. @dabbott continues to have the same maintainer access as when he worked here, per our policy.

**Comment by dabbott** [comment]
I'm using Lona for my own projects, so I'll still be maintaining it. I'll be adding little things incrementally as I need them. 

Honestly it's probably too hard for anybody else to use in its current state, but once you know how to use it you can build interfaces at least 3-4x faster, so it's worth the time to maintain 😆.

**Comment by outdooricon** [comment]
@ljharb, can you speak to airbnb's perspective on their support of the future of this project beyond @dabbott's willingness to maintain its current state? Some of us at Target are very interested in exploring this project, and it would be nice to know where airbnb stands...

**Comment by ljharb** [comment]
@outdooricon any and all projects need people willing and able to maintain them :-) this is @dabbott’s project, so I’d suggest working with them to try to become collaborators - at which point, the bus factor would go up, and there’d be no danger of a lack of owners for the project :-)

In general, Airbnb will be a good steward of all of its projects as long as it can, and when it can’t, we’ll work to come up with a way to ensure that the project’s users aren’t left in the lurch.

**Comment by outdooricon** [comment]
Ok, thanks @ljharb for helping to clarify!

@dabbott I'd really, really like to chat with you more off-thread about Lona and the future, how can I reach you?

**Comment by dabbott** [comment]
@outdooricon Probably Twitter is easiest to start, and then we can figure it out from there. You can DM me at https://twitter.com/dvnabbott
