### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by thealjey** [airbnb/Lona#172]
Sorry for a potentially useless issue, but how far do you think this project is from being 
production-ready?
Is it going to be a few months/years, or is there a specific list of things that need to be done?

**Comment by dabbott** [comment]
It really depends on the feature you're looking to use. E.g. in terms of code generation, Swift is pretty far along and React Native is getting there, but Android hasn't been started. As a rough ballpark, I would say 2-3 months of active development.

I'm currently figuring out how I can keep working on this. I don't really have a roadmap now that I'm not at Airbnb anymore, but possibly I will come up with one soon. Things are sort of in flux at the moment.

**Comment by omegasoft7** [comment]
@dabbott If you make the roadmap I am sure a lot of developers are willing to help you reach the goals. I am one of them and I really liked the idea and will support you as well.

**Comment by dabbott** [comment]
There's a roadmap now! https://github.com/airbnb/Lona/issues/222
