### ISSUE TITLE
Update Text Style picker UI to match color picker UI

### ISSUE THREAD

**Issue by dabbott** [airbnb/Lona#20]

**Comment by NghiaTranUIT** [comment]
Hi @dabbott , this project is amazing idea 👍 
To be honest,  I and designer/android team are struggling this exactly situation in every time you're facing. I love this idea so much.

I'm wondering if you're working on this issues or not ?
If not I'm willing to contribute my effort on my spare time 😃

**Comment by dabbott** [comment]
@NghiaTranUIT I'm really glad you like the project. I have faced this problem so many times... but I think we can finally solve it! 

I haven't started working on this issue. I would love if you could do it 😄 . Let me know if you run into any issues or want to discuss more.

**Comment by NghiaTranUIT** [comment]
Ok, Let me do it 👍

**Comment by dabbott** [comment]
Closed with https://github.com/airbnb/Lona/pull/31!
