### ISSUE TITLE
How to export Sketch files into .component format

### ISSUE THREAD

**Issue by Eishpirate** [airbnb/Lona#22]
It would be good if we had some documentation on how to export Sketch files into the .component JSON file format.

That would allow Designers with a less technical bent to be more fully involved in the project and generate some traction.

**Comment by dabbott** [comment]
Yes, totally! Currently there's no way to go from Sketch -> .component, but we're actively exploring how to do that. This project probably isn't ready for non-technical designers yet, since it's still very very rough. We'll for sure add way more docs when it's ready.

Closing this for now

**Comment by awinogradov** [comment]
Do you have specification for `.component` format? So, I can help ;)
