### ISSUE TITLE
Amend readme to indicate which file to open

### ISSUE THREAD

**Issue by danhollick** [airbnb/Lona#25]
The readme doesn't specify which file to open in XCode: The  `LonaStudio.xcodeproj` or the `LonaStudio.xcworkspace`

If you open the `LonaStudio.xcodeproj`  file and try to build that, you will get some module errors ie:
`No such module 'Lottie'`.

So just to avoid confusion maybe it would be best to indicate this in the readme.

**Comment by dabbott** [comment]
Yep, good point.

**Comment by dabbott** [comment]
Done!
