### ISSUE TITLE
Installing on a fresh macbook

### ISSUE THREAD

**Issue by ohld** [airbnb/Lona#267]
Hi there! I'm trying to test your app, but I have not do any iOS development. 

I've tried to do [these commands](https://github.com/airbnb/Lona/blob/master/studio/README.md):
``` bash
cd studio
bundle && bundle exec pod install
carthage bootstrap --new-resolver --platform macOS
```

But it failed.

I was asked to install **carthage**. The installation command: 
``` bash
brew install carthage
```

After I have received an error:
``` bash
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
```
and this solved this problem: https://stackoverflow.com/questions/40743713/command-line-tool-error-xcrun-error-unable-to-find-utility-xcodebuild-n.

May be this will be useful to update installation instructions.

**Comment by dabbott** [comment]
Thanks for pointing this out @ohld! I'll definitely update the instructions.
