### ISSUE TITLE
Add Screenshots? 🙀

### ISSUE THREAD

**Issue by lukasoppermann** [airbnb/Lona#27]
Hey, 

I am very confused as to what Lona (Studio) is. Could you maybe attach some screenshots of the app so one can get an Idea what it is and how to work with it? That would be neat.

Yes, I know its a dev preview, but more people testing = better, right? 🙃

Thanks

**Comment by dabbott** [comment]
Hey! I open sourced this super early so I can start chatting/collaborating with other folks working on design tools... but it isn't really ready for non-contributors to test.

I'm for sure gonna add screenshots and documentation when it's ready for a broader audience to try it out. In the meantime, you're welcome to build it 😉
