### ISSUE TITLE
Problems with building workspace

### ISSUE THREAD

**Issue by dennislaupman** [airbnb/Lona#28]
Hello!

When I try to run the "LonaStudio.xcworkspace" in Xcode Version 9.0 beta 5 (9M202q).

The build failed:

![image](https://user-images.githubusercontent.com/1274858/33424243-8074dace-d5bb-11e7-805e-06ce465ea8f6.png)

Okay I found more information:
_According to the beta 5 release notes:_
_"Building macOS apps with the AVFoundation framework is not supported with Xcode 9 beta 5."_
 
Is it possible to fix this?

Thanks in advance

Dennis

**Comment by dabbott** [comment]
Hmm... based on that error message, I'm wondering if it'll build for you in Xcode 9 non-beta? I use AVFoundation for exporting animations to video, so I don't think I can solve that.

**Comment by haswalt** [comment]
I can’t vouch for beta but built with no issues in Xcode 9.

Make sure you’ve run pod install and opened the workspace.

Maybe try clearing the derived data folder and doing a build clean.

Harry Walter

M: +44 (0)784 9503 950<tel:+44%20784%209503%20950>
W: harrywalter.co.uk<http://harrywalter.co.uk/>

On 4 December 2017 at 20:22:36, Devin Abbott (notifications@github.com<mailto:notifications@github.com>) wrote:

Hmm... based on that error message, I'm wondering if it'll build for you in Xcode 9 non-beta? I use AVFoundation for exporting animations to video, so I don't think I can solve that.

**Comment by dennislaupman** [comment]
Hi @dabbott, @haswalt,

I downgraded my Xcode. I'm now able to build Lona and that has solved the problem!
Thanks for your support. 

Dennis
