### ISSUE TITLE
Canvas heights not set by default

### ISSUE THREAD

**Issue by dennislaupman** [airbnb/Lona#33]
Hi,

When I open a new project, The canvas width is set by default to the correct 375px, but the height doesn't. The height is set to 100px. Is there a reason for that?

![image](https://user-images.githubusercontent.com/1274858/33685953-8423c21c-dad3-11e7-9765-4b888ecba283.png)

Otherwise I will change it and send a pull request :P

Grtz Dennis

**Comment by dennislaupman** [comment]
See pull request #34

**Comment by dennislaupman** [comment]
Hello Devin,

>> The main use case of Lona Studio (for us right now, at least) is designing individual components,

Ahhhh that clarifies a lot.

I also have some ideas about this. I will work this out and post it.

What I wondered. Where are the parameter values set? The demo texts, images etc? I can see them in the demo component (card). But not in the GUI.

Greetings Dennis

PS. Is it an idea to setup a Gitter?  Thats works great for brainstorms

**Comment by dabbott** [comment]
Let me think about the Gitter a bit... I'm thinking _not yet_ since I'm not sure I'll have the time to stay on top of it at the moment. But this could be a good idea when I have a little more bandwidth in the future. Let's stick to Github issues for now but revisit if it becomes a hassle.

The parameters come from *Cases* in this example (definitely need a better way to visualize where parameters come from)

![screen shot 2017-12-07 at 2 11 03 pm](https://user-images.githubusercontent.com/1198882/33741282-8f3f53c0-db58-11e7-96d1-ad6b802d0394.png)

**Comment by haswalt** [comment]
So far I see 2 good solutions:

1. Given that a  lot of the UI decision have been taken from Sketch start with no canvases defined. this implies that the canvas is based on your decisions.
2. Start with (n) clearly labeled phone sizes. This will give a guide to new users to what they may be building, coming from design land I often start with a full screen design and break down into components once I have an idea of the styling. Most small agencies and individuals don't have a full DLS setup before starting a project.

**Comment by dennislaupman** [comment]
Hi Devin, Haswalt,

I think it is easier to give them the choice of canvas or component for they begin. See my (quick) concept.

![welcome_to_lona](https://user-images.githubusercontent.com/1274858/33744239-9c333080-dbb0-11e7-9423-a57902d4fcaf.png)

After they make a choice we can set te canvas to the immediately height.

**Comment by dabbott** [comment]
Right, creating two different starting "templates" (Canvas/Screen or Component) seems reasonable.

#### Pros
- Clarity around your _intent_ will help us choose a better default state for your new component

#### Cons
- Fundamentally Lona only has "components", so the choice is kind of misleading. E.g. if I open up a saved file, I might wonder whether it's a canvas or a component, but that distinction doesn't actually exist.

I think it could just be a matter of naming. I think this could work if we called them "templates", or something that implies that you're just picking a starting point, but after that it's fully configurable.

(related: https://github.com/airbnb/Lona/issues/11)

**Comment by dennislaupman** [comment]
AHhhh okay... Now I understand :P 

2 new ideas:

Welcome screen:

![welcome_to_lona_take_2](https://user-images.githubusercontent.com/1274858/33763940-acbf83c4-dc12-11e7-8516-630415ef47b9.png)

Or in the GUI just like Sketch?: 

![image](https://user-images.githubusercontent.com/1274858/33763880-71d1f85a-dc12-11e7-944f-b4c822a72a1d.png)

Or... both

**Comment by dennislaupman** [comment]
Okay I read # 11 (I had missed it). Initially the Workspace is always the starting point?

**Comment by dabbott** [comment]
@dennislaupman I like this direction overall. It's clear which workspace I'm using, and I can see which components I can open.

I might tweak it so both "new component" and "open component" can be accessed from the same screen: 

![bitmap](https://user-images.githubusercontent.com/1198882/33783227-b4b8c52e-dc10-11e7-92c2-80ad65f5edda.png)

As some other inspiration, I think photoshop does this pretty well, and is closer to our use case than e.g. the Sketch or Framer launch screens:

![screen_shot_2017-12-08_at_12_02_53_pm](https://user-images.githubusercontent.com/1198882/33783308-1d4cc144-dc11-11e7-9f99-f379500f3e43.png)

![screen_shot_2017-12-08_at_12_02_47_pm](https://user-images.githubusercontent.com/1198882/33783399-75090eb0-dc11-11e7-8be9-7d850a20326c.png)

**Comment by dennislaupman** [comment]
Oww wow yes, thats looks great! (I'm still using C6 :P)

**Comment by dennislaupman** [comment]
Maybe its a good idea to combine this issue with #11?

**Comment by dabbott** [comment]
Good idea. Closing this one.
