### ISSUE TITLE
[Lona Studio] Display SVG files when selected within the file navigator

### ISSUE THREAD

**Issue by dabbott** [airbnb/Lona#339]
## Summary

Currently Lona Studio displays some image files, e.g. PNG files, when selected in the file navigator. However, it doesn't display SVG files, which it really should, since it handles them elsewhere correctly.

Here's what the image viewer looks like for PNG files:

![Screen Shot 2019-03-12 at 11 08 36 AM](https://user-images.githubusercontent.com/1198882/54224809-8609bd80-44b7-11e9-846c-e8e0f06a8ac2.png)

And here's what it _currently_ looks like for SVG files:

![Screen Shot 2019-03-12 at 11 08 43 AM](https://user-images.githubusercontent.com/1198882/54224823-8bff9e80-44b7-11e9-8a5a-b29b400a48bd.png)

We want to use the same viewer as the PNG for SVG also.

## Proposed Implementation

I think we want to add `svg` to the list of supported file types:

![Screen Shot 2019-03-12 at 11 12 17 AM](https://user-images.githubusercontent.com/1198882/54224971-df71ec80-44b7-11e9-9e07-f98041f25da0.png)

Then when we read the data for the `ImageDocument`
https://github.com/airbnb/Lona/blob/0571d6aa7c7796073eece13aa6a43acdb15840c7/studio/LonaStudio/Documents/ImageDocument.swift#L45 we should render the SVG file to an image
https://github.com/airbnb/Lona/blob/0571d6aa7c7796073eece13aa6a43acdb15840c7/studio/LonaStudio/Models/SVG.swift#L416

We might need to choose an arbitrary size for the image. We could use the `viewBox` of the svg to attempt to determine an "intrinsic" size of some kind, but that isn't really reliable. SVGs are designed to scale to any size, so they don't really have an intrinsic size, although `viewBox` is sometimes used like that. Maybe play around with it and see what looks best?

> If you want to try using the viewBox, it's a little more effort, but you can access it by first generating an `SVG.Node` before rendering an image, e.g. here https://github.com/airbnb/Lona/blob/0571d6aa7c7796073eece13aa6a43acdb15840c7/studio/LonaStudio/Models/SVG.swift#L241

**Comment by klymenkoo** [comment]
I want to take this issue as well.

**Comment by klymenkoo** [comment]
I was able to display SVG images, but some images are rendered with pure black color for some reason (look screenshot 2):
<img width="300" alt="Screen Shot 2019-03-12 at 10 11 23 PM" src="https://user-images.githubusercontent.com/26641473/54248647-dca4e500-4513-11e9-86e0-613b1ff3f7a7.png">
<img width="300" alt="Screen Shot 2019-03-12 at 10 11 43 PM" src="https://user-images.githubusercontent.com/26641473/54248649-dca4e500-4513-11e9-9270-e56f4b38ada1.png">
<img width="300" alt="Screen Shot 2019-03-12 at 10 11 34 PM" src="https://user-images.githubusercontent.com/26641473/54248648-dca4e500-4513-11e9-931c-471f07da693d.png">

Any thoughts on what might cause this problem?

**Comment by dabbott** [comment]
I'm not sure, but those SVGs most likely use features that Lona's very primitive SVG renderer doesn't support yet. E.g. the firefox one might have gradients, but we can only draw solid colors for now. So I think what you have looks good.
