### ISSUE TITLE
[Lona Studio] Implement bottom pane hide/show

### ISSUE THREAD

**Issue by dabbott** [airbnb/Lona#356]
## Summary

This button _should_ hide/show the bottom section of the UI, but currently it does nothing!

![Screen_Shot_2019-03-23_at_4_16_20_PM](https://user-images.githubusercontent.com/1198882/54872785-32d11e00-4d87-11e9-9075-6e0fc1977e98.png)

Let's fix that. Some new users have been pretty confused by why the bottom hasn't been responding...

## Proposed Implementation

When the `activePanes` change... https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/WorkspaceViewController.swift#L84

We currently ignore the bottom pane: https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/WorkspaceViewController.swift#L301

Instead, we need to hide/show the `bottomItem` in the `ComponentEditorViewController`: https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/ComponentEditorViewController.swift#L213-L216

The easiest way to do this is probably to expose the `bottomItem` as a _public or internal_ variable of the `ComponentEditorViewController`, but this isn't a great approach, since then we're exposing implementation details to a parent view controller. If we make `bottomItem` a member variable, it should be _private_.

Instead, let's add a variable `var utilitiesViewVisible: Bool` (with a `didSet` block) to `ComponentEditorViewController`, which we can then update from the `WorkspaceViewController`. The `WorkspaceViewController` contains an instance of `ComponentEditorViewController` we can use: https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/WorkspaceViewController.swift#L127

We'll also need to add/copy something similar to `setVisibility` into `ComponentEditorViewController` to do the actual hiding/showing.
https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/WorkspaceViewController.swift#L305-L315

> For bonus points, also update the splitter https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/ComponentEditorViewController.swift#L151 to have a thickness of 0 when the bottom pane is hidden: https://github.com/airbnb/Lona/blob/9ee49dfbb9d3dce6309c90b93c51c6949cf4f214/studio/LonaStudio/Workspace/SectionSplitter.swift#L22

I'd recommend starting by setting a breakpoint in `activePanes` so you can see how clicking the toolbar button updates this value and take it from there.

**Comment by klymenkoo** [comment]
I'll take this issue.

**Comment by mathieudutour** [comment]
This is fixed right?
