### ISSUE TITLE
[Lona Studio] Delete files by pressing "Delete" button

### ISSUE THREAD

**Issue by klymenkoo** [airbnb/Lona#358]
## Summary of Idea

At the moment, you can delete files in the file navigator only by using the context menu. It would be really nice to be able to delete files just by pressing "delete" button.

## Expected Behavior
A user should select a file and press "delete" button on the keyboard.

## Current Behavior
A user has to select file, right click it, and select "Delete" option.
<img width="407" alt="Screen Shot 2019-03-27 at 6 56 39 PM" src="https://user-images.githubusercontent.com/26641473/55117844-8793d200-50c2-11e9-918a-516e44d3aeea.png">

```

**Comment by mathieudutour** [comment]
i'd say it's usually cmd + delete, not just delete

**Comment by dabbott** [comment]
Great suggestion!

I just tried in VSCode and Xcode, and it looks like its just Delete, but then it prompts for confirmation. I think we could do the same. Cmd+Delete would work too, although I would still want to prompt for confirmation, so I don't think the Cmd is needed at that point.

![Screenshot_3_28_19__12_02_PM](https://user-images.githubusercontent.com/1198882/55185380-76de6d00-5151-11e9-9b19-2fe0f4f282ff.png)

![Screenshot_3_28_19__12_03_PM](https://user-images.githubusercontent.com/1198882/55185455-96759580-5151-11e9-9691-3838b5f7e26f.png)

**Comment by mathieudutour** [comment]
Oh interesting, for me vs code only cmd + delete works and there is no confirm alert. 

Maybe I click on the do not ask me again once
