### ISSUE TITLE
Importing for example sketch

### ISSUE THREAD

**Issue by dennislaupman** [airbnb/Lona#39]
What will be the right method:

First of all I'm a Sketch user, that's why I approach this as starting point:

- Syncing (if possible). You need to open Sketch and if you update your design, Lona will ask you if you want to update your component.
- Export trough a export (Skewtch) plugin
- Import file in Lona

Last question: have you already started with the import?

**Comment by btn0s** [comment]
I've been thinking about this a lot today as well, I think the better question to ask might be: Where does Lona fit into a workflow? What's the ideal workflow built around Lona?

Personally I don't really know what that might look like, but it's a conversation we should have as this grows. Also-- How does this play with [`react-sketchapp`](https://github.com/airbnb/react-sketchapp)?

**Comment by dennislaupman** [comment]
Yes, Correct! 

What really bothers me at the moment is the prototypes (made with Framer, Origami) are usable for production. If the UX prototype is finished, everything has to be converted to code. If we could build a bridge between design tools like Sketch and code frameworks such as React (native), we could save a lot of work.

> How does this play with react-sketchapp?
I don't know ;) I Desning in Code does'nt work for me (maybe that's a shortcoming for me :P) What I would really like is 

1. Sketch (Component Design) 
2. Lona (Small Logic, Like switch on / off) 
3. React (native) component (Code)

**Comment by dabbott** [comment]
Sketch sync would be awesome but not high priority IMO, since Lona is more focused on the part of the workflow after Sketch.
