### ISSUE TITLE
Are there any plan to build viewer for `.component` ?

### ISSUE THREAD

**Issue by omuomugin** [airbnb/Lona#411]
Hi there I'm very fan of this project and I played around with this tools and CLI tools.
And I came up with an idea and I wanted to ask this could be in your road map or not.

## Summary of Idea
I slightly understand what Lona Studio wanted to do.
However I guess it is not easy to build editor for mac app (as there seem to have some performance issues). 
So how about building some viewer app or web front.

I think what is good about `.component` is completely independent from platform and has simple data format to represent designs of the components.
And I wanted to use to generate documentation from it.
It will be more like IDL for web api and `.component` for design components.

I'll be looking forward that this project to be public sometime in near future.

**Comment by omuomugin** [comment]
maybe this is what I was looking for?
https://github.com/airbnb/Lona/tree/master/compiler/generate-docs

**Comment by mathieudutour** [comment]
Kind of. There is the Lona compiler that generates React components from .component files. So you can use those react components to build a viewer if you’d like to. 

But Lona Studio is working fine :)
The `generate-docs` is a work in progress for the moment but we will soon have some improvements on that side!
