### ISSUE TITLE
Is there any documents using Lona?

### ISSUE THREAD

**Issue by trustyoo86** [airbnb/Lona#460]
## Summary

Question that use other company's design system.

## Contents

Hello,
I'm front-end engineer in e-commerce company.
Our team planning to convesion from legacy to react, and I found this project that utilities for design systems.

But, I can't find enough document that I understand this project.
Is there different from `react-sketchapp`? And If our team apply this in our project, How can I do first?

**Comment by jamesjara** [comment]
same question, thanks

**Comment by dabbott** [comment]
- `react-sketchapp`: generate a Sketch file using React + a framework very similar to React Native
- `Lona`: define your components/shared styles using a _custom configuration format_ and generate: a Sketch file, documentation website, React, iOS, and Android code

Lots of updates/new docs hopefully coming soon!

**Comment by vasicvuk** [comment]
@dabbott Since there is no update for a long time now, I would like if this project is still developed and maintained or not ?

Thanks

**Comment by jamesjara** [comment]
still wondering about
