### ISSUE TITLE
No such module "ThemedColor"

### ISSUE THREAD

**Issue by jannikrl** [airbnb/Lona#481]
## Expected Behavior
Being able to build Lona in Xcode

## Current Behavior
When I build Lona in Xcode I get the error: "No such module 'ThemedColor'".

ThemedColor is imported in the file NavigationItemStack.swift in the BreadcrumbBar package. ThemedColor seems not to be used in the file, so maybe the import is not necessary?

<img width="1298" alt="Skærmbillede 2020-04-05 kl  15 38 54" src="https://user-images.githubusercontent.com/1298449/78499863-91c7c200-7753-11ea-8f79-f8e6079987cf.png">

**Comment by mathieudutour** [comment]
Did you install the carthage dependencies?

**Comment by jannikrl** [comment]
I just ran the below Carthage command just to be sure. When I build the project I still see the error.

`carthage bootstrap --new-resolver --platform macOS`

**Comment by dabbott** [comment]
This is a bug, perhaps due to Swift PM packages not being resolved to a specific version. I'll fix it.

**Comment by dabbott** [comment]
This should hopefully be fixed on master now!

**Comment by jannikrl** [comment]
Beautiful. It works!
