### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by dabbott** [airbnb/Lona#5]
Here are some of the high level tasks I'd like to work on in the near-term. All of these are fairly nuanced, so if you're gonna pick one up, we should talk about it beforehand.

## Design
- [x] Add landing page that allows workspace selection and shows the contents of the workspace #11
- [ ] Lona Studio UI overhaul - let's try to make things simpler and more designer friendly. Smart defaults, but you can dig in deeper when needed. Example: a visual way to add new canvases and cases directly from the canvas area
- [ ] Direction manipulation - at the _most basic level_, components on the canvas should highlight when they're selected. Then we can do fancier things
- [ ] Debugger - it's very difficult to trace the flow of values through a component, since parameters can come from so many different places, and null values are silently ignored
- [x] Add a saved/unsaved indicator to the Lona Studio UI. Currently there's no indication that a component file is unsaved
- [x] Add global undo/redo to the Lona Studio UI. Currently there's no undo/redo
- [x] Nullable parameters. Many parameters are nullable. E.g. `top: 0` is different than no `top` at all. The UI should allow this null state.
- [x] Allow component interactivity. First step: pressed state. How do we change the UI when pressed?
- [ ] Better component picker UI (reuse whatever we use in landing page?)
- [x] Better UI for text style picker

## Code Generation
- [x] Update compiler to support latest file format (in progress)
- [x] Generate Swift code (in progress)
- [x] "Dogfood" `.component` files by using them to build the UI of Lona Studio
- [ ] Use `id` for layers and other things, instead of name. Automatically create name from `id`. Enforce uniqueness.

## Misc
- [ ] Finish fully documenting the `.component` file format
- [x] Image asset paths should be relative to the workspace
- [x] Add shadow support
- [ ] We should watch the workspace for changes so you don't have to press reload manually
- [x] Upgrade to Swift 4

**Comment by ljharb** [comment]
Also:
## Testing
- [ ] add automated tests
- [ ] gate merging on travis-ci passing those tests

**Comment by ruswerner** [comment]
@dabbott I'm curious what your workflow is for getting Sketch assets into Lona? Do you manually rebuild the UI in Lona Studio, or do you have a converter that transforms the Sketch json into your component json format? If nothing exists yet, that's cool, but I'd be keen to know your thoughts around  the ideal/eventual workflow from Sketch to code. Cheers.

**Comment by dabbott** [comment]
@ruswerner I think there should be a converter. Right now there isn't one, so we've been building UI in Lona Studio. It wouldn't be too hard to write a converter, but maintaining it for Sketch releases going forward would be very time-consuming.

The Sketch format is missing a lot of info needed to make a good `.component`. The converter's output will be a good starting point for the visuals, but will still need to be augmented with layout and state information.

**Comment by ruswerner** [comment]
@dabbott I've been working on similar things at Atomic.io recently and this really caught my eye. I'd like to chat with you a bit more about this sometime soon. What's the best way to DM you?

**Comment by dabbott** [comment]
@ruswerner Probably Twitter. Happy to chat.

**Comment by dylanslewis** [comment]
@dabbott love the look of Lona as a tool for being the source of truth of the design system, but won't the code exports suffer from the same issues as Zeplin where it's still a very manual process to generate the new code and update all existing references in the project? This also seems to assume that every project would want the same style of code exported, which may conflict with requirements such as supporting accessibility.

I've just released v1 of [stylesync](https://github.com/dylanslewis/stylesync) which is a command line tool to export from Sketch, but I've got an [Issue](https://github.com/dylanslewis/stylesync/issues/23) to support other inputs (including Lona). It uses templates to export the code, so can be extremely versatile in the languages or platforms it supports, and actively updates references within the project to account for things like a style's name changing, or being removed from the design system whilst still being used in the project.

Whilst stylesync needs a bit more work to fully support all components from Lona, I was wondering how you'd feel about considering it for the code generation side of things? It's great to see so many good tools emerging in the design system space, and it'd be great to collaborate.

**Comment by dabbott** [comment]
@dylanslewis this looks really cool! It seems like it could make sense for generating things like color and text styles, and is much more fully thought through than what I've cobbled together so far. I think generating the actual view hierarchy code is going to have to happen in this repo due to its complexity, but delegating to stylesync for Sketch interop and styles is worth considering.

1. Can you move this to a separate github issue and remove it from here?

2. You free to sync up over video or something and give me a quick overview of stylesync?

**Comment by dylanslewis** [comment]
Yeah it’s responsibility isn’t really for the hierarchy code, but I think it can definitely work for the code generation and Sketch imports with a bit more work on my side.

> Can you move this to a separate github issue and remove it from here?

Yep, will do this later tonight

> You free to sync up over video or something and give me a quick overview of stylesync?

Sounds good, what works best for you?
