### ISSUE TITLE
Undo/Redo Mechanism

### ISSUE THREAD

**Issue by NghiaTranUIT** [airbnb/Lona#56]
## Suggesting a New Feature

The undo/redo mechanism is a must-have functionality on any kind of design tool. So it's high priority to implement this feature carefully.

## Initial Design

In order to implement the Undo/Redo mechanism, we take an advantage of Command Design Pattern, which is one of famous pattern from Gang Of Four.

### Command
`Command` is abstract protocol, which defines the receiver and how to execute and undo an action

<img width="254" alt="screen shot 2018-01-13 at 9 55 20 am" src="https://user-images.githubusercontent.com/5878421/34902139-e385d7cc-f847-11e7-99ab-5d736134deb8.png">

All of change actions logic, such as UpdateValueCommand, UpdateColorCommand, UpdateShadowCommand, ... should be encapsulated into the `Command`'s adopting class.

<img width="933" alt="screen shot 2018-01-13 at 9 42 33 am" src="https://user-images.githubusercontent.com/5878421/34902048-2dd19afc-f846-11e7-9895-4bc5d46ba4a8.png">

### Global Command Queue
In order to support Undo/Redo mechanism globally, we define the queue, which holds 20 commands at most (configurable). It simply appends new command and pop out the latest command if it exceeds the threshold.
<img width="997" alt="screen shot 2018-01-13 at 9 43 31 am" src="https://user-images.githubusercontent.com/5878421/34902052-3c957450-f846-11e7-9d0f-2a3e25aa4729.png">

### Undo/Redo action
<img width="981" alt="screen shot 2018-01-13 at 9 43 42 am" src="https://user-images.githubusercontent.com/5878421/34902053-45163fec-f846-11e7-81cd-f28759654e77.png">
We define currentIndex, which is responsible for current action has been taken place. 

As a result, the `Undo` action simply invokes the `redo` action of current action, then moving the pointer back.
`Redo` action simply invokes the `execute` action of next command in the queue.

### New action while in middle of actions
<img width="981" alt="screen shot 2018-01-13 at 9 47 55 am" src="https://user-images.githubusercontent.com/5878421/34902101-2245a808-f847-11e7-91b5-09c874b478b3.png">
If the current pointer is in middle of the queue. It means the user does couple of redo, then executing new command. 

I suggest to drop all ahead actions and replace with new one. It's same behavior with Sketch or Photoshop.

## Proposed Implementation in Swift
`Command` protocol defines essential actions.
```swift
protocol Command {
    var receiver: Receivable { get }
    func execute()
    func undo()
}
```
`Subclass` of `Command` is responsible for passing the `execute` action and `undo` action to `receiver`. `Command` subclass doesn't know concrete implementation, it's de-coupling and could be reused easily in any Lona Component.

For instance, `UpdateShadowCommand` could pass effortlessly the action to the TextLabel (use NSAttributeString) or UIView (CALayer or shadow property) and doesn't care how to support Shadow on specific views.
```swift
struct UpdateShadowCommand: Command {
    private let newShadow: NSShadow
    private let oldShadow: NSShadow
    private let _receiver: UpdateShadowReceivable
    var receiver: Receivable { return _receiver }
    
    init(receiver: UpdateShadowReceivable, newShadow: NSShadow, oldShadow: NSShadow) {
        self._receiver = receiver
        self.newShadow = newShadow
        self.oldShadow = oldShadow
    }
    
    func execute() {
        _receiver.update(shadow: newShadow)
    }
    
    func undo() {
        _receiver.update(shadow: oldShadow)
    }
}
```
On the other hand, `Receivable` is placeholder protocol, which represent any kind object or view in Lona.
```swift
protocol Receivable {}
```
```swift
protocol UpdateShadowReceivable: Receivable {
    func update(shadow: NSShadow)
}
```

For instance, TextLabel adopts `UpdateShadowReceivable` and `UpdateTextStylyReceivable`. After that, TextLabel could actually implement the logic.
```swift
class TextLabel {
    private var shadow: NSShadow?
    var textStyle: String = "April"
}

extension TextLabel: UpdateShadowReceivable {
    func update(shadow: NSShadow) {
        self.shadow = shadow
        // Render NSShadow by NSAttributeString
    }
}

extension TextLabel: UpdatedTextStyleReceivable {
    func update(textStyle: String) {
        self.textStyle = textStyle
       // Render TextStyle by NSFont
    }
}
```
Box also adopts the `UpdateShadowReceivable` protocol and write the logic as well.
```swift
class Box: NSView {
    private var shadow: NSShadow?
}

extension Box: UpdateShadowReceivable {
    func update(shadow: NSShadow) {
        self.shadow = shadow
        // Render Shadow by shadow layer property
    }
}
```

`CommandManager` is the big guy, who put the dirty hand into the real work. Basically, it manages the command queue by appending or dropping certain commands. `CommandManager` also offers the shared global instance, so we could leverage it in any part of the codebase.
The implement is straightforward. It looks at the currentCommandIndex and do appropriate action on the queue in order to achieve Undo/Redo behavior.
```swift
class CommandManager: Commander {
    
    static let shared = CommandManager()
    
    private var queue: [Command] = []
    private var currentCommandIndex: Int = -1
    
    func execute(_ command: Command) {
        
        // In middle
        // Replace the right array with new command
        if currentCommandIndex < queue.count - 1 {
            let _range = NSRange(location: currentCommandIndex, length: queue.count - currentCommandIndex)
            let range = Range(_range)!
            queue.removeSubrange(range)
        }
        
        queue.append(command)
        command.execute()
        currentCommandIndex += 1
    }
    
    func undo() {
        guard ... {}
        
        let command = queue[currentCommandIndex]
        command.undo()
        currentCommandIndex -= 1
    }
    
    func redo() {
        guard ... {}
   
        currentCommandIndex += 1
        let command = queue[currentCommandIndex]
        command.execute()
    }
}
```

## How to use 
```swift
let commander = CommandManager.shared
let text = TextLabel()

// Do actions
let action = UpdateTextStyleCommand(receiver: text, new: "SF_20", old: text.textStyle)
commander.execute(action)

// Undo
commander.undo()

// Undo
commander.redo()
```

## Plan
1. Implement the foundation of the Undo/Redo.
2. Write tests and make sure they passes all ordinary cases and certain edge cases.
3. Convert all available actions to Commands
4. Adopts `Receivable` and provide the concrete implementations.
5. Support Undo/Redo globally.

## References
1. [Wikipedia Command Pattern](https://en.wikipedia.org/wiki/Command_pattern)

-----------
Looking forward to hearing your feedback @dabbott  😸

**Comment by dabbott** [comment]
It will be so amazing to have undo/redo support! It can be very frustrating without it... making a change and then forgetting how to get back to where I was.

I think the Command pattern is a great choice here 👍 

The main things that come to mind:
1. It seems like Apple provides a pretty comprehensive [Undo manager](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/UndoArchitecture/Articles/UndoManager.html#//apple_ref/doc/uid/20000205-CJBDJCCJ), with [built-in support for AppKit](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/UndoArchitecture/Articles/AppKitUndo.html#//apple_ref/doc/uid/20000213-CJBJBEII) features. I haven't tried using it before, but it does seem like it provides a lot features we'd want out-of-the-box (`NSTextView` integration, `NSMenu` integration, command grouping, etc). It also seems like they've thought about a lot of the tricky coordination stuff, e.g. managing a separate undo stack per `NSDocument` and per `NSTextView`. It looks like it's an implementation of the Command pattern... do you think we'd be able to use this?
2. In most places, we'll want to make sure our undo/redo logic applies to the data models, rather than the views. E.g. when we want to update a shadow, we should update the `shadow` property of the `CSLayer` model:
https://github.com/airbnb/Lona/blob/f4e766a5ebf407a7ebf0f774f59ce615b16fdcbd/LonaStudio/Models/CSLayer.swift#L316-L319
And then trigger a UI update within the main `ViewController`:
https://github.com/airbnb/Lona/blob/f4e766a5ebf407a7ebf0f774f59ce615b16fdcbd/LonaStudio/Workspace/ViewController.swift#L413-L414
I suspect the main `ViewController` will need to handle most undo/redo actions, since it contains both the data models and the UI views. We'll also need to keep a separate undo stack per `NSDocument`, so we'll have to figure out how to coordinate that with the `ViewController`.
3. It _could_ make sense to use closures for encapsulating Command logic, rather than a protocol that various classes implement. E.g. 
    ```swift
    struct Command {
      let undo: () -> Void
      let redo: () -> Void
    }
    ```
    The advantage of this is that we don't have to explicitly create different implementations of the `Command` protocol. It'll also be easier to colocate the code for performing and undoing a command (since we don't have to make a separate function for each). The disadvantage is that there isn't as much information when debugging (e.g. there isn't a `newShadow` and `oldShadow` property to inspect). This _may_ depend whether we use Apple's undo manager, so we should figure that out first.

Thanks for the detailed writeup, that made it very easy to understand. I'm really excited about this one -- Lona will be a lot easier to use once it has undo/redo!

Anyway, what do you think?

(PS: I'm very close to .component -> Swift code generation... it's gonna be SO good!)

**Comment by ilanbrnd** [comment]
Yes, I would recommend not trying to do an end-run around NSUndoManager. Keep stuff simple and leverage the existing architecture as much as possible.

**Comment by ilanvolow** [comment]
As a previous Mac desktop developer in another life, I agree with your assessment. Keep things simple the existing architecture as (eg. NSUndoManager) as much as possible.

**Comment by NghiaTranUIT** [comment]
I agree with you guys @dabbott and @ilanvolow. I forgot that Apple's already provided us the power tool like NSUndoManager 👍 

I'm doing some research about it then heading back to see the 3rd's option is acceptable or not. Since I prefer to create different implementations of the `Command` protocol than general-purpose protocol.

Thank you for your feedback 👍 😄

**Comment by NghiaTranUIT** [comment]
Sorry for doing this work later than I expected due to busy work at Zalora.
I've spent time for researching and doing little experience on UndoManager. 

It's the potential candidate in order to replace my `CommandManager` since I support seamlessly must-have functionalities like grouping command as long as Cocoa Kit integration.

They offer cumbersome func, such as
```swift
func registerUndo(withTarget target: Any, selector: Selector, object anObject: Any?)
```
IMO, It's super cumbersome 🥒 

I prefer to use their convention closure 
```swift
func setShadow(_ shadow: CShadow) {
let shadow = CSShadow()
undoManager?.registerUndo(withTarget: self, handler: { [oldShadow = shadow] (MyViewController) -> (target) in
		target.setShadow(oldShadow)
	})
}
```
However, sometime it could be a boilerplate. So I will mix-up two approach by creating closure or initilaizing the `UpdateShadowCommand`.

Let try first then evaluating the effort and trade-off 😄

**Comment by NghiaTranUIT** [comment]
I'm working on it now to see how to tackle it efficiently 👍

**Comment by ilanvolow** [comment]
A good rule of thumb in general would be to check to make sure Apple hasn’t already implemented something already before taking it on. If you’re used to the JavaScript development world where there’s 8 different non-standard implementations of something basic that you have to painfully sift and sort through (before getting disgusted and writing a 9th one), having great stuff like a One True Apple-Sanctioned And Supported Undo Manager, Color Picker, etc can something easily overlooked.

**Comment by dabbott** [comment]
Done!
