### ISSUE TITLE
Color picker crashes

### ISSUE THREAD

**Issue by ilanvolow** [airbnb/Lona#58]
Steps to reproduce:

1. Build and run Lona.
2. Select "View" from sidebar
3. Scroll down to the "Color" area and click the "Custom color" button.
4. Type the character 'a' in the "Search Color..." searchfield
5. Hit the Enter key.
6. An index out of range error occurs in the setupSearchView method of the PickerView extension.

**Comment by dabbott** [comment]
Thanks for reporting.

@NghiaTranUIT I can take a look at this, unless you want to. I'm gonna try to merge in the first pass of my Swift code generation stuff today or tomorrow and can look at this after.
