### ISSUE TITLE
Coding conventions (SwiftLint)

### ISSUE THREAD

**Issue by huyphams** [airbnb/Lona#62]
## Suggesting a New Feature

Hi folks, I just came here and I see something. Lona is in the first stage of development and still missing coding conventions. There are also have some invalid configs. It would be great if we have rules for coding. It makes Lona code readable and clean.

## Proposed Implementation

- What do you guys think about to add [SwiftLint](https://github.com/realm/SwiftLint) to Lona? 
- Remove invalid configs (invalid target) and update .gitignore.
- After adding SwiftLint, we will have a lot of convention warnings => refactor it.

## Submitting a Bug Report

- If you guys interesting in my suggestion, I can give a PR 😄

**Comment by NghiaTranUIT** [comment]
It's cool @huyphams.
Regrading to SwiftLint - I honestly love it. 

I intend to integrate TravisCI as long as the bot from [Danger System](http://danger.systems) in next PR. The conjunction of them are so perfectly for an OSS. It strictly keeps our style convention and contributors on right track 👍

**Comment by dabbott** [comment]
@huyphams Sounds fantastic! This will be really helpful for new folks looking to contribute.

👍 👍 👍

**Comment by huyphams** [comment]
Hey thanks, I'm working on it. I will create a PR on Sunday 😄

**Comment by dabbott** [comment]
Merged! I guess next step is to fix all the warnings? 😭

**Comment by huyphams** [comment]
Thanks!!!
`Merged! I guess next step is to fix all the warnings? 😭` => yeah, but don't worry. I'm here 😄

**Comment by dabbott** [comment]
SwiftLint is 💯 . Thanks for adding it!
