### ISSUE TITLE
please upgrade .ruby-version (activesupport requires Ruby version >= 2.2.2.)

### ISSUE THREAD

**Issue by ryh** [airbnb/Lona#69]
## Submitting a Bug Report
OS: macOS 10.13.2
ruby: 2.0.0-p648 (from .ruby-version in repo) REF:#41
## Current Behavior
gem install cannot install `cocoapods` with .ruby-version `2.0.0-p648`
>ERROR: Error installing cocoapods-core:
activesupport requires Ruby version >= 2.2.2.

Please  upgrade ruby version and `.ruby-version`

**Comment by dabbott** [comment]
Yeah, that sounds good. I've just been using a different version and ignoring this...

I'm going to wait till SwiftLint lands, since that affects pods and project structure https://github.com/airbnb/Lona/pull/70

**Comment by dabbott** [comment]
Upgraded!

**Comment by dabbott** [comment]
I'm not sure. Does the ruby version affect how cocoapods get installed?
