### ISSUE TITLE
Enable SwiftLint plugin

### ISSUE THREAD

**Issue by NghiaTranUIT** [airbnb/Lona#73]
## Suggesting a New Feature

We finally integrated `SwiftLint` and `Danger.System` into Lona system.

In order to improve efficient cooperatation. I suggest enabling the Swiftlint plugin in DangerFile. Thus, the `LonaBot` can shot a warning if there are any violation code in his PRs 😄 

## Proposed Implementation

1. Uncomment the trigger https://github.com/airbnb/Lona/blob/276f937e256072b316455dd98f571e7f6851b5aa/Dangerfile#L29

2. Enable `danger-swiftlint` gem https://github.com/airbnb/Lona/blob/276f937e256072b316455dd98f571e7f6851b5aa/Gemfile#L9

## 
@dabbott Please let me know when you finish the fixing of SwiftLint, so I will do this PR asap 👍

**Comment by dabbott** [comment]
Yes, this sounds great :+1:! Just need to fix the lint issues...

**Comment by dabbott** [comment]
Merged! https://github.com/airbnb/Lona/pull/80
