### ISSUE TITLE
Support View borderWidth and borderColor when generating Swift code

### ISSUE THREAD

**Issue by dabbott** [airbnb/Lona#83]
## Summary

Let's update the Swift code generation to support `borderWidth` and `borderColor`.

## Initial Design

Lona Studio already allows editing these styles:

![screen shot 2018-01-29 at 5 00 24 pm](https://user-images.githubusercontent.com/1198882/35542652-ee4f9af0-0515-11e8-8911-c197bd8fd600.png)

## Proposed Implementation

I'm trying to support both iOS and OSX where possible, so:
- On iOS, I think we can use the `borderWidth` and `borderColor` properties of `CALayer`. We'll just need to convert our `UIColor`s to `CGColor`s.
- On OSX, I've been avoiding layer-backed/hosted views, so we should go with the `borderColor` and `borderWidth` of `NSBox` (currently Lona `View` maps to `NSBox`). We'll also need to set `borderType = .lineBorder` I think.

For now, assume that only Lona `View` can have a `borderWidth` and `borderColor`. Adding a border to a Lona `Text` or `Image` is undefined behavior (even though Lona Studio allows it... I may remove).

#### Compiler

In the Reason code, we'll start by defining the type and default value of these new styles:

https://github.com/airbnb/Lona/blob/master/compiler/core/src/core/decode.re#L5-L31
https://github.com/airbnb/Lona/blob/master/compiler/core/src/core/lonaValue.re#L19-L46

Conveniently the names are the same as the names defined in JSON, but we'll need to convert the color we use to `cgColor` on iOS. The general idea is that you'll overwrite the `BinaryExpression` AST node to specifically catch and rewrite this case. As an example, here's how I convert `text`-related things to use `attributedText` and `attributedStringValue`:

https://github.com/airbnb/Lona/blob/master/compiler/core/src/swift/swiftLogic.re#L156

It's not the prettiest, but it works for now. I think once I have a better sense of all the possible use cases, I'll introduce an abstraction that isn't based on string replacement.

## Test Plan

To test, create a new component in the `examples/test` workspace that has a border style, and re-generate the swift code for this workspace from the `compiler/core` directory with `node src/main.bs.js workspace swift ../../examples/test ../../examples/generated/test/swift`.

To test for OSX, I haven't started saving the snapshots (I definitely should), but just run `node src/main.bs.js workspace swift ../../examples/test ../../examples/generated/test/osx --framework=appkit`

You can try running this component in a blank iOS app or maybe a playground. I made a little testing app that I haven't committed yet, since I'm still trying to think of the best way to test all these easily.

When you commit your changes, DO commit the generated swift files. They're basically a snapshot test that lets us easily catch changes.

@jasonzurita

**Comment by jasonzurita** [comment]
@dabbott What a great breakdown!! I will keep you updated as I work though this 😀!

**Comment by NghiaTranUIT** [comment]
Excellent proposal @dabbott. I'm working on Undo/Redo now, then looking forward to contribute next features 👍

**Comment by dabbott** [comment]
@jasonzurita I updated the compiler package with a command for generating the test files. You can run `yarn snapshot` and it'll generate the JS and Swift workspaces. https://github.com/airbnb/Lona/blob/3bdf32586197231319781238e5bd5931cea1be5b/compiler/core/package.json#L21

No rush @NghiaTranUIT, everything you've done so far has been great!
