### ISSUE TITLE
Default workspace config

### ISSUE THREAD

**Issue by brentvatne** [airbnb/Lona#9]
It might be nice to provide some simple default configuration when creating a workspace, so there are is a basic color palette and text styles that demo what you can do. It would make it easier for people to try the project out.

**Comment by dabbott** [comment]
Totally! This is the very next thing I'm gonna push up. I have a branch with a material design one. I'm home for Thanksgiving till Monday though, so... probably you'll have more luck waiting till then.

**Comment by dabbott** [comment]
Done. Very primitive, but here it is https://github.com/airbnb/Lona/tree/master/examples/material-design
